#
# This source file is part of the Bramble open source project.
#
# Copyright (c) 2026 Jaldis B.V.
#
# Licensed under the MIT OR Apache-2.0 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import annotations

from typing import Annotated, Union

import pytest
from bramble._bramble import SchemaError, describe_union

import bramble
from bramble._union import resolve_union_type


class AudioRecord:
    pass


class VideoRecord:
    pass


@bramble.type
class Audio:
    title: str


@bramble.type
class Video:
    title: str


@bramble.type
class Image:
    title: str


# `typing.get_type_hints` can't see an enclosing test function's local scope, so a union alias
# referenced from a field annotation must live at module level (same gotcha as test_schema.py).
_MediaItem = Annotated[Union[Audio, Video], bramble.union("MediaItem")]


def test_bare_union_gets_autogenerated_name() -> None:
    info = describe_union(Union[Audio, Video, Image])
    assert info.name == "AudioVideoImage"
    assert info.member_names == ["Audio", "Video", "Image"]
    assert info.has_custom_resolve_type is False


def test_named_union_via_annotated() -> None:
    MediaItem = Annotated[Union[Audio, Video, Image], bramble.union("MediaItem")]
    info = describe_union(MediaItem)
    assert info.name == "MediaItem"
    assert info.member_names == ["Audio", "Video", "Image"]


def test_union_with_description() -> None:
    MediaItem = Annotated[
        Union[Audio, Video, Image],
        bramble.union("MediaItem", description="a media item"),
    ]
    info = describe_union(MediaItem)
    assert info.description == "a media item"


def test_single_member_union() -> None:
    SingleMedia = Annotated[Audio, bramble.union("SingleMedia")]
    info = describe_union(SingleMedia)
    assert info.name == "SingleMedia"
    assert info.member_names == ["Audio"]


def test_union_with_custom_resolve_type_dispatches_correctly() -> None:
    def resolve_type(obj: object, info: object) -> type:
        if isinstance(obj, AudioRecord):
            return Audio
        if isinstance(obj, VideoRecord):
            return Video
        return Image

    MediaItem = Annotated[
        Union[Audio, Video, Image],
        bramble.union("MediaItem", resolve_type=resolve_type),
    ]
    info = describe_union(MediaItem)
    assert info.has_custom_resolve_type is True

    definition = MediaItem.__metadata__[0]
    members = [Audio, Video, Image]

    assert resolve_union_type(definition, members, AudioRecord(), info=None) is Audio
    assert resolve_union_type(definition, members, VideoRecord(), info=None) is Video
    assert resolve_union_type(definition, members, object(), info=None) is Image


def test_union_without_resolve_type_falls_back_to_isinstance() -> None:
    MediaItem = Annotated[Union[Audio, Video, Image], bramble.union("MediaItem")]
    definition = MediaItem.__metadata__[0]
    members = [Audio, Video, Image]

    audio = Audio(title="song")
    video = Video(title="clip")

    assert resolve_union_type(definition, members, audio, info=None) is Audio
    assert resolve_union_type(definition, members, video, info=None) is Video


def test_resolve_union_type_with_no_definition_falls_back_to_isinstance() -> None:
    members = [Audio, Video, Image]
    audio = Audio(title="song")

    assert resolve_union_type(None, members, audio, info=None) is Audio


def test_no_matching_member_raises_graphql_error() -> None:
    with pytest.raises(bramble.GraphQLError) as excinfo:
        resolve_union_type(None, [Audio, Video], object(), info=None)

    assert excinfo.value.code is bramble.ErrorCode.UNION_TYPE_RESOLUTION_FAILED


def test_resolve_type_returning_non_member_raises_graphql_error() -> None:
    def bad_resolve_type(obj: object, info: object) -> type:
        return str

    definition = bramble.union("Media", resolve_type=bad_resolve_type)

    with pytest.raises(bramble.GraphQLError) as excinfo:
        resolve_union_type(definition, [Audio, Video], object(), info=None)

    assert excinfo.value.code is bramble.ErrorCode.UNION_TYPE_RESOLUTION_FAILED


# GraphQL unions may only contain object types (never a scalar or an interface), a check added to
# `describe_union` (Rust) after this session found that a bare scalar `Union[int, str]` silently
# produced invalid SDL with no validation at all.


def test_raises_on_scalar_union_member() -> None:
    with pytest.raises(SchemaError, match="union member 'Int' is not a"):
        describe_union(Union[Audio, int])


def test_raises_on_interface_union_member() -> None:
    @bramble.interface
    class Node:
        @bramble.field
        def id() -> bramble.ID:
            return "1"

    with pytest.raises(SchemaError, match="union member 'Node' is not a"):
        describe_union(Union[Audio, Node])


def test_union_reused_across_multiple_fields_prints_once_in_sdl() -> None:
    @bramble.type
    class Query:
        @bramble.field
        def a() -> _MediaItem:
            return Audio(title="x")

        @bramble.field
        def b() -> _MediaItem:
            return Video(title="y")

    schema = bramble.Schema(query=Query, types=[Audio, Video])
    sdl = schema.to_sdl()

    assert sdl.count("union MediaItem") == 1
    assert "union MediaItem = Audio | Video" in sdl


def test_optional_union_field_resolves_to_none() -> None:
    @bramble.type
    class Query:
        @bramble.field
        def maybe_media() -> _MediaItem | None:
            return None

    schema = bramble.Schema(query=Query, types=[Audio, Video])

    assert schema.execute("{ maybeMedia { __typename } }") == {"data": {"maybeMedia": None}}


def test_optional_union_field_resolves_to_a_member() -> None:
    @bramble.type
    class Query:
        @bramble.field
        def maybe_media() -> _MediaItem | None:
            return Video(title="clip")

    schema = bramble.Schema(query=Query, types=[Audio, Video])

    assert schema.execute("{ maybeMedia { __typename ... on Video { title } } }") == {
        "data": {"maybeMedia": {"__typename": "Video", "title": "clip"}}
    }


# --- Lazy union members -------------------------------------------------------------------------


def test_a_union_member_may_be_a_lazy_reference(tmp_path, monkeypatch) -> None:
    """A union whose members live in another module has to name them lazily, and a genuine import
    cycle leaves no alternative. Members used to be read verbatim off `get_args`, so such a member
    arrived as the `Annotated` wrapper and was rejected as not being an object type.
    """
    import sys
    import textwrap

    package = tmp_path / "lazyunion"
    package.mkdir()
    (package / "__init__.py").write_text("")
    (package / "other.py").write_text(
        textwrap.dedent(
            """
            import bramble

            @bramble.type
            class Video:
                url: str
            """
        )
    )
    (package / "main.py").write_text(
        textwrap.dedent(
            """
            from typing import Annotated, Union
            import bramble

            @bramble.type
            class Audio:
                url: str

            Media = Annotated[
                Union[Audio, Annotated["Video", bramble.lazy(".other")]],
                bramble.union("Media"),
            ]

            @bramble.type
            class Query:
                @bramble.field
                def media() -> Media:
                    return Audio(url="a.mp3")
            """
        )
    )

    monkeypatch.syspath_prepend(str(tmp_path))
    for name in [n for n in sys.modules if n.startswith("lazyunion")]:
        del sys.modules[name]

    from lazyunion import main

    sdl = bramble.Schema(query=main.Query).to_sdl()
    assert "union Media = Audio | Video" in sdl
