from __future__ import annotations

from typing import Annotated, Union

import pytest

import bramble
from bramble._bramble import describe_union
from bramble._union import resolve_union_type


class AudioRecord:
    pass


class VideoRecord:
    pass


@bramble.type
class Audio:
    title: str


@bramble.type
class Video:
    title: str


@bramble.type
class Image:
    title: str


def test_bare_union_gets_autogenerated_name() -> None:
    info = describe_union(Union[Audio, Video, Image])
    assert info.name == "AudioVideoImage"
    assert info.member_names == ["Audio", "Video", "Image"]
    assert info.has_custom_resolve_type is False


def test_named_union_via_annotated() -> None:
    MediaItem = Annotated[Union[Audio, Video, Image], bramble.union("MediaItem")]
    info = describe_union(MediaItem)
    assert info.name == "MediaItem"
    assert info.member_names == ["Audio", "Video", "Image"]


def test_union_with_description() -> None:
    MediaItem = Annotated[
        Union[Audio, Video, Image],
        bramble.union("MediaItem", description="a media item"),
    ]
    info = describe_union(MediaItem)
    assert info.description == "a media item"


def test_single_member_union() -> None:
    SingleMedia = Annotated[Audio, bramble.union("SingleMedia")]
    info = describe_union(SingleMedia)
    assert info.name == "SingleMedia"
    assert info.member_names == ["Audio"]


def test_union_with_custom_resolve_type_dispatches_correctly() -> None:
    def resolve_type(obj: object, info: object) -> type:
        if isinstance(obj, AudioRecord):
            return Audio
        if isinstance(obj, VideoRecord):
            return Video
        return Image

    MediaItem = Annotated[
        Union[Audio, Video, Image],
        bramble.union("MediaItem", resolve_type=resolve_type),
    ]
    info = describe_union(MediaItem)
    assert info.has_custom_resolve_type is True

    definition = MediaItem.__metadata__[0]
    members = [Audio, Video, Image]

    assert resolve_union_type(definition, members, AudioRecord(), info=None) is Audio
    assert resolve_union_type(definition, members, VideoRecord(), info=None) is Video
    assert resolve_union_type(definition, members, object(), info=None) is Image


def test_union_without_resolve_type_falls_back_to_isinstance() -> None:
    MediaItem = Annotated[Union[Audio, Video, Image], bramble.union("MediaItem")]
    definition = MediaItem.__metadata__[0]
    members = [Audio, Video, Image]

    audio = Audio(title="song")
    video = Video(title="clip")

    assert resolve_union_type(definition, members, audio, info=None) is Audio
    assert resolve_union_type(definition, members, video, info=None) is Video


def test_resolve_union_type_with_no_definition_falls_back_to_isinstance() -> None:
    members = [Audio, Video, Image]
    audio = Audio(title="song")

    assert resolve_union_type(None, members, audio, info=None) is Audio


def test_no_matching_member_raises_graphql_error() -> None:
    with pytest.raises(bramble.GraphQLError) as excinfo:
        resolve_union_type(None, [Audio, Video], object(), info=None)

    assert excinfo.value.code is bramble.ErrorCode.UNION_TYPE_RESOLUTION_FAILED


def test_resolve_type_returning_non_member_raises_graphql_error() -> None:
    def bad_resolve_type(obj: object, info: object) -> type:
        return str

    definition = bramble.union("Media", resolve_type=bad_resolve_type)

    with pytest.raises(bramble.GraphQLError) as excinfo:
        resolve_union_type(definition, [Audio, Video], object(), info=None)

    assert excinfo.value.code is bramble.ErrorCode.UNION_TYPE_RESOLUTION_FAILED
