//
// This source file is part of the Bramble open source project.
//
// Copyright (c) 2026 Jaldis B.V.
//
// Licensed under the MIT OR Apache-2.0 license (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://opensource.org/licenses/MIT
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

use bramble_core::schema::UnionDefinition;
use pyo3::prelude::*;

use crate::type_info::SchemaError;
use crate::typing_utils::{find_marker, is_union_origin, lazy_type_class, named_type_name, unwrap_annotated};

#[pyclass(name = "UnionInfo", frozen, skip_from_py_object)]
pub struct PyUnionInfo {
    #[pyo3(get)]
    pub name: String,
    #[pyo3(get)]
    pub description: Option<String>,
    #[pyo3(get)]
    pub member_names: Vec<String>,
    #[pyo3(get)]
    pub has_custom_resolve_type: bool,
    /// Not Python-exposed -- see `PyTypeInfo::definition`'s doc comment for why.
    pub definition: UnionDefinition,
}

impl From<UnionDefinition> for PyUnionInfo {
    fn from(union: UnionDefinition) -> Self {
        Self {
            name: union.name.clone(),
            description: union.description.clone(),
            member_names: union.member_names.clone(),
            has_custom_resolve_type: union.has_custom_resolve_type,
            definition: union,
        }
    }
}

/// Extracts a union's member types plus its name/description/resolver, from either declaration
/// form per §5: bare `Union[A, B, C]` (name autogenerated by concatenating member names, matching
/// the single-member case `Annotated[A, bramble.union(...)]` where `Union[A]` collapses to just
/// `A` -- Python's typing module doesn't represent a union of one type as a distinct construct),
/// or `Annotated[Union[A, B, C], bramble.union("Name", ...)]` for an explicit name/description/
/// custom `resolve_type`.
#[pyfunction]
pub fn describe_union(py: Python<'_>, annotation: &Bound<'_, PyAny>) -> PyResult<PyUnionInfo> {
    let typing = py.import("typing")?;
    let (underlying, metadata) = unwrap_annotated(&typing, annotation.clone())?;

    let union_class = py.import("bramble._union")?.getattr("UnionDefinition")?;
    let union_marker = find_marker(&metadata, &union_class)?;

    let origin = typing.call_method1("get_origin", (&underlying,))?;
    let members: Vec<Bound<PyAny>> = if is_union_origin(py, &origin)? {
        typing
            .call_method1("get_args", (&underlying,))?
            .try_iter()?
            .collect::<PyResult<_>>()?
    } else {
        vec![underlying.clone()]
    };

    // GraphQL unions may only contain object types (never a scalar, interface, or input type) --
    // a builtin/custom scalar has no `__bramble_type_info__` at all, while an interface/input has
    // one but with the wrong `kind`, so both are rejected the same way. A `bramble.lazy(...)`
    // placeholder is exempted: it has no `__bramble_type_info__` either (its whole point is to
    // avoid an import at this stage), so its real kind isn't knowable yet -- accepted here,
    // trusting it, with no equivalent re-check once `_schema.py`'s graph walk resolves it for
    // real. A lazy-referenced union member that turns out to be a scalar/interface won't be
    // caught by this check; an accepted, narrow gap rather than a silent one.
    for member in &members {
        if member.is_instance(lazy_type_class(py)?)? {
            continue;
        }
        let kind: Option<String> = member
            .getattr("__bramble_type_info__")
            .ok()
            .and_then(|info| info.getattr("kind").ok())
            .and_then(|kind| kind.extract().ok());
        if kind.as_deref() != Some("type") {
            let member_name = named_type_name(py, member)?;
            return Err(SchemaError::new_err(format!(
                "union member '{member_name}' is not a '@bramble.type'-decorated object type; \
                 GraphQL unions may only contain object types"
            )));
        }
    }

    let member_names = members
        .iter()
        .map(|member| named_type_name(py, member))
        .collect::<PyResult<Vec<_>>>()?;

    let (name, description, has_custom_resolve_type) = match &union_marker {
        Some(marker) => {
            let name: String = marker.getattr("name")?.extract()?;
            let description: Option<String> = marker.getattr("description")?.extract()?;
            let resolve_type = marker.getattr("resolve_type")?;
            (name, description, !resolve_type.is_none())
        }
        None => (member_names.concat(), None, false),
    };

    let definition = UnionDefinition {
        name,
        description,
        member_names,
        has_custom_resolve_type,
    };

    Ok(PyUnionInfo::from(definition))
}

#[cfg(test)]
mod tests {
    use super::*;
    use pyo3::types::PyDict;

    fn describe(py: Python<'_>, setup: &str, expression: &str) -> PyResult<UnionDefinition> {
        let globals = PyDict::new(py);
        crate::test_support::ensure_bramble_importable(py);
        py.run(std::ffi::CString::new(setup).unwrap().as_c_str(), Some(&globals), None)?;
        let annotation = py.eval(std::ffi::CString::new(expression).unwrap().as_c_str(), Some(&globals), None)?;
        Ok(describe_union(py, &annotation)?.definition)
    }

    const TYPES: &str = "import bramble\nfrom typing import Annotated, Union\n@bramble.type\nclass A:\n    x: str\n@bramble.type\nclass B:\n    x: str\n";

    #[test]
    fn a_marked_union_keeps_its_declared_name_and_members() {
        Python::attach(|py| {
            let def = describe(py, TYPES, "Annotated[Union[A, B], bramble.union('Media', description='d')]").unwrap();
            assert_eq!(def.name, "Media");
            assert_eq!(def.description.as_deref(), Some("d"));
            assert_eq!(def.member_names, vec!["A".to_string(), "B".to_string()]);
            assert!(!def.has_custom_resolve_type);
        });
    }

    #[test]
    fn a_bare_union_gets_an_autogenerated_name() {
        Python::attach(|py| {
            let def = describe(py, TYPES, "Union[A, B]").unwrap();
            // Member names concatenated, matching what `test_bare_union_gets_autogenerated_name`
            // asserts from the Python side.
            assert_eq!(def.name, "AB");
        });
    }

    #[test]
    fn a_custom_resolve_type_is_flagged() {
        Python::attach(|py| {
            let def = describe(
                py,
                TYPES,
                "Annotated[Union[A, B], bramble.union('Media', resolve_type=lambda obj, info: A)]",
            )
            .unwrap();
            assert!(def.has_custom_resolve_type);
        });
    }

    #[test]
    fn a_scalar_union_member_is_rejected() {
        // A union may only contain object types; a scalar member could never be matched by a
        // `... on Member` selection.
        Python::attach(|py| {
            let error = describe(py, TYPES, "Union[A, int]").expect_err("a scalar member is invalid");
            assert!(error.to_string().contains("not a"), "unexpected: {error}");
        });
    }
}
