#
# This source file is part of the Bramble open source project.
#
# Copyright (c) 2026 Jaldis B.V.
#
# Licensed under the MIT OR Apache-2.0 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any

from bramble._error import ErrorCode, GraphQLError


class UnionDefinition:
    """What `bramble.union(...)` produces -- a marker attached to a `Union[...]` annotation via
    `typing.Annotated`, carrying the union's GraphQL name and optional `resolve_type` callback.
    """

    def __init__(
        self,
        name: str,
        description: str | None = None,
        resolve_type: Callable[[Any, Any], type] | None = None,
    ) -> None:
        self.name = name
        self.description = description
        self.resolve_type = resolve_type


def union(
    name: str,
    description: str | None = None,
    resolve_type: Callable[[Any, Any], type] | None = None,
) -> UnionDefinition:
    """Names a GraphQL union over a `typing.Union` of object types.

        MediaItem = Annotated[Union[Audio, Video], bramble.union("MediaItem")]

        @bramble.type
        class Query:
            @bramble.field
            def media() -> MediaItem: ...

    A bare `Union[Audio, Video]` also works and gets an autogenerated name; the marker exists to
    give the union a stable, intentional one (plus a description).

    At execution time a union resolves to a concrete member by `isinstance` against each member in
    turn -- exactly one must match. Pass `resolve_type=lambda obj, info: SomeMember` when that isn't
    enough: unions have no shared base class to hang an `is_type_of` on, which is why they use a
    callback where interfaces don't. A `resolve_type` returning a non-member is an error, not a
    silent pass-through.

    Arguments:
        name: the GraphQL union name.
        description: rendered as the union's SDL description.
        resolve_type: called with `(value, info)` to pick the concrete member class.
    """
    return UnionDefinition(name=name, description=description, resolve_type=resolve_type)


def resolve_union_type(
    definition: UnionDefinition | None,
    members: Sequence[type],
    obj: Any,
    info: Any,
) -> type:
    """Determines which of a union's member types a resolved value is.

    Uses the union's custom `resolve_type` callback if one was declared (per §5, a bramble
    addition since a union has no shared base class to hang a per-member `is_type_of` on);
    otherwise falls back to an `isinstance` check against each member, same as interfaces.
    """
    tagged = getattr(obj, "__bramble_concrete_type__", None)
    if tagged is not None and tagged in members:
        return tagged

    if definition is not None and definition.resolve_type is not None:
        resolved = definition.resolve_type(obj, info)
        if resolved not in members:
            member_names = ", ".join(member.__name__ for member in members)
            raise GraphQLError(
                f"resolve_type returned '{getattr(resolved, '__name__', resolved)}', which is "
                f"not a member of this union ({member_names})",
                code=ErrorCode.UNION_TYPE_RESOLUTION_FAILED,
            )
        return resolved

    matches = [member for member in members if isinstance(obj, member)]

    if not matches:
        member_names = ", ".join(member.__name__ for member in members)
        raise GraphQLError(
            f"no member type matched the resolved value (tried: {member_names})",
            code=ErrorCode.UNION_TYPE_RESOLUTION_FAILED,
        )
    if len(matches) > 1:
        match_names = ", ".join(member.__name__ for member in matches)
        raise GraphQLError(
            f"resolved value matched more than one union member: {match_names}",
            code=ErrorCode.UNION_TYPE_RESOLUTION_FAILED,
        )

    return matches[0]
