use bramble_core::schema::GraphQLType;
use pyo3::prelude::*;

use crate::union_info::describe_union;

/// `typing.get_origin(int | None)` and `typing.get_origin(typing.Optional[int])` both denote a
/// union, but which singleton object represents "union" isn't guaranteed stable across Python
/// versions (some versions unify `types.UnionType` and `typing.Union`, some don't) -- so this
/// checks identity against both rather than assuming either alone is sufficient.
pub fn is_union_origin(py: Python<'_>, origin: &Bound<'_, PyAny>) -> PyResult<bool> {
    let typing_union = py.import("typing")?.getattr("Union")?;
    if origin.is(&typing_union) {
        return Ok(true);
    }
    let types_union = py.import("types")?.getattr("UnionType")?;
    Ok(origin.is(&types_union))
}

/// Unwraps `Annotated[T, ...]` to `(T, metadata)`. Non-`Annotated` annotations pass through
/// unchanged with empty metadata.
pub fn unwrap_annotated<'py>(
    typing: &Bound<'py, PyAny>,
    annotation: Bound<'py, PyAny>,
) -> PyResult<(Bound<'py, PyAny>, Vec<Bound<'py, PyAny>>)> {
    let origin = typing.call_method1("get_origin", (&annotation,))?;
    let annotated = typing.getattr("Annotated")?;
    if !origin.is(&annotated) {
        return Ok((annotation, Vec::new()));
    }

    let args: Vec<Bound<PyAny>> = typing
        .call_method1("get_args", (&annotation,))?
        .try_iter()?
        .collect::<PyResult<_>>()?;
    let mut args = args.into_iter();
    let underlying = args.next().expect("Annotated[T, ...] always has an underlying type");

    Ok((underlying, args.collect()))
}

/// Finds the first item in `metadata` that's an instance of `marker_class`, if any.
pub fn find_marker<'py>(
    metadata: &[Bound<'py, PyAny>],
    marker_class: &Bound<'py, PyAny>,
) -> PyResult<Option<Bound<'py, PyAny>>> {
    for value in metadata {
        if value.is_instance(marker_class)? {
            return Ok(Some(value.clone()));
        }
    }
    Ok(None)
}

/// Resolves a Python type annotation to a `GraphQLType`. Handles `Optional[T]`/`T | None`
/// (nullable, no `NonNull` wrapper), `list[T]`/`List[T]` (`GraphQLType::List`), and
/// `Annotated[T, ...]` (metadata is irrelevant to the *type*, just unwrapped). Anything not
/// explicitly wrapped nullable is `NonNull` by default, matching how Python's own convention
/// (no `| None` means required) already lines up with GraphQL's.
pub fn resolve_graphql_type(
    py: Python<'_>,
    typing: &Bound<'_, PyAny>,
    annotation: &Bound<'_, PyAny>,
) -> PyResult<GraphQLType> {
    let (core, nullable) = resolve_core(py, typing, annotation)?;
    if nullable {
        Ok(core)
    } else {
        Ok(GraphQLType::NonNull(Box::new(core)))
    }
}

/// Returns `(core_type, is_nullable_at_this_level)` -- the type as it would be if this level
/// turns out nullable, without the `NonNull` wrapper `resolve_graphql_type` adds when it isn't.
fn resolve_core(
    py: Python<'_>,
    typing: &Bound<'_, PyAny>,
    annotation: &Bound<'_, PyAny>,
) -> PyResult<(GraphQLType, bool)> {
    let origin = typing.call_method1("get_origin", (annotation,))?;

    let annotated = typing.getattr("Annotated")?;
    if origin.is(&annotated) {
        let args = typing.call_method1("get_args", (annotation,))?;
        let underlying = args.get_item(0)?;
        return resolve_core(py, typing, &underlying);
    }

    if is_union_origin(py, &origin)? {
        let members: Vec<Bound<PyAny>> = typing
            .call_method1("get_args", (annotation,))?
            .try_iter()?
            .collect::<PyResult<_>>()?;
        let none_type = py.None().into_bound(py).get_type();
        let non_none: Vec<Bound<PyAny>> = members.into_iter().filter(|member| !member.is(&none_type)).collect();

        if non_none.len() == 1 {
            // Optional[T]: nullable, using T's own core (T's own nullability marker, if T were
            // itself somehow also optional, is irrelevant -- Optional[...] already established
            // nullable at this level).
            let (core, _) = resolve_core(py, typing, &non_none[0])?;
            return Ok((core, true));
        }

        // A genuine multi-member union with no `None` (a bramble union, most likely) -- a single
        // named type by its own registered/autogenerated name, non-null unless wrapped in
        // Optional[...] at an outer level.
        let union_info = describe_union(py, annotation)?;
        return Ok((GraphQLType::Named(union_info.name), false));
    }

    if origin.eq(py.get_type::<pyo3::types::PyList>())? || origin.eq(py.get_type::<pyo3::types::PyTuple>())? {
        let args = typing.call_method1("get_args", (annotation,))?;
        let element = args.get_item(0)?;
        let inner = resolve_graphql_type(py, typing, &element)?;
        return Ok((GraphQLType::List(Box::new(inner)), false));
    }

    // A leaf/named type.
    Ok((GraphQLType::Named(named_type_name(py, annotation)?), false))
}

fn named_type_name(py: Python<'_>, annotation: &Bound<'_, PyAny>) -> PyResult<String> {
    let builtins = py.import("builtins")?;
    if annotation.is(&builtins.getattr("str")?) {
        return Ok("String".to_string());
    }
    if annotation.is(&builtins.getattr("bool")?) {
        // Must be checked before `int`: Python's `bool` is a subclass of `int`, but identity
        // comparison against the exact `int`/`bool` class objects below isn't affected by that
        // subclass relationship either way -- this ordering is just for readability.
        return Ok("Boolean".to_string());
    }
    if annotation.is(&builtins.getattr("int")?) {
        return Ok("Int".to_string());
    }
    if annotation.is(&builtins.getattr("float")?) {
        return Ok("Float".to_string());
    }

    if annotation.is(&py.import("bramble")?.getattr("ID")?) {
        return Ok("ID".to_string());
    }

    let datetime_module = py.import("datetime")?;
    if annotation.is(&datetime_module.getattr("datetime")?) {
        return Ok("DateTime".to_string());
    }
    if annotation.is(&datetime_module.getattr("date")?) {
        return Ok("Date".to_string());
    }
    if annotation.is(&py.import("decimal")?.getattr("Decimal")?) {
        return Ok("Decimal".to_string());
    }
    if annotation.is(&py.import("uuid")?.getattr("UUID")?) {
        return Ok("UUID".to_string());
    }

    if let Ok(info) = annotation.getattr("__bramble_type_info__") {
        return info.getattr("name")?.extract();
    }

    // A custom scalar's `NewType` (or any other otherwise-unrecognized type): its GraphQL name
    // isn't knowable here (scalar registration happens later, at `Schema()`, via
    // `config.scalar_map`) -- fall back to the type's own `__name__`, which is also the
    // convention `bramble.scalar(name=...)` follows by default (a `Base64 = NewType("Base64",
    // bytes)` typically registers a scalar named "Base64" to match).
    if let Ok(name_attr) = annotation.getattr("__name__")
        && let Ok(name) = name_attr.extract::<String>()
    {
        return Ok(name);
    }

    annotation.str()?.extract()
}
