use bramble_core::schema::UnionDefinition;
use pyo3::prelude::*;

use crate::typing_utils::{find_marker, is_union_origin, unwrap_annotated};

#[pyclass(name = "UnionInfo", frozen, skip_from_py_object)]
pub struct PyUnionInfo {
    #[pyo3(get)]
    pub name: String,
    #[pyo3(get)]
    pub description: Option<String>,
    #[pyo3(get)]
    pub member_type_reprs: Vec<String>,
    #[pyo3(get)]
    pub has_custom_resolve_type: bool,
    /// Not Python-exposed -- see `PyTypeInfo::definition`'s doc comment for why.
    pub definition: UnionDefinition,
}

impl From<UnionDefinition> for PyUnionInfo {
    fn from(union: UnionDefinition) -> Self {
        Self {
            name: union.name.clone(),
            description: union.description.clone(),
            member_type_reprs: union.member_type_reprs.clone(),
            has_custom_resolve_type: union.has_custom_resolve_type,
            definition: union,
        }
    }
}

fn member_name(member: &Bound<'_, PyAny>) -> PyResult<String> {
    member.getattr("__name__")?.extract()
}

fn member_type_repr(member: &Bound<'_, PyAny>) -> PyResult<String> {
    member.str()?.extract()
}

/// Extracts a union's member types plus its name/description/resolver, from either declaration
/// form per §5: bare `Union[A, B, C]` (name autogenerated by concatenating member names, matching
/// the single-member case `Annotated[A, bramble.union(...)]` where `Union[A]` collapses to just
/// `A` -- Python's typing module doesn't represent a union of one type as a distinct construct),
/// or `Annotated[Union[A, B, C], bramble.union("Name", ...)]` for an explicit name/description/
/// custom `resolve_type`.
#[pyfunction]
pub fn describe_union(py: Python<'_>, annotation: &Bound<'_, PyAny>) -> PyResult<PyUnionInfo> {
    let typing = py.import("typing")?;
    let (underlying, metadata) = unwrap_annotated(&typing, annotation.clone())?;

    let union_class = py.import("bramble._union")?.getattr("UnionDefinition")?;
    let union_marker = find_marker(&metadata, &union_class)?;

    let origin = typing.call_method1("get_origin", (&underlying,))?;
    let members: Vec<Bound<PyAny>> = if is_union_origin(py, &origin)? {
        typing
            .call_method1("get_args", (&underlying,))?
            .try_iter()?
            .collect::<PyResult<_>>()?
    } else {
        vec![underlying.clone()]
    };

    let member_type_reprs = members
        .iter()
        .map(member_type_repr)
        .collect::<PyResult<Vec<_>>>()?;

    let (name, description, has_custom_resolve_type) = match &union_marker {
        Some(marker) => {
            let name: String = marker.getattr("name")?.extract()?;
            let description: Option<String> = marker.getattr("description")?.extract()?;
            let resolve_type = marker.getattr("resolve_type")?;
            (name, description, !resolve_type.is_none())
        }
        None => {
            let mut autogenerated_name = String::new();
            for member in &members {
                autogenerated_name.push_str(&member_name(member)?);
            }
            (autogenerated_name, None, false)
        }
    };

    let definition = UnionDefinition {
        name,
        description,
        member_type_reprs,
        has_custom_resolve_type,
    };

    Ok(PyUnionInfo::from(definition))
}
